### ISSUE TITLE
H264 Encoder could not find hardware decoder, switched to default and then failed to process initial FLUSH command on H.264 MFT Error:80004005

### ISSUE THREAD

**Issue by Ragingram2** [Ezharjan/UnityVideoStreamingPackage#1]
When trying to stream a 128x96 @30/1fps  at 100000 bytes/s, Unity script fails silently. We turned on tracing for dll and rebuilt, which then gave us this log
[H264Encoder.log](https://github.com/Ezharjan/UnityVideoStreamingPackage/files/6123455/H264Encoder.log)

After some research, the error is "Unspecified" (Thanks for the great description Microsoft!). We think it may have to do with a missing codec on our side but are unsure. 

Have you experienced anything like this?

P.S: Great project btw. We have been looking for a solution to streaming scene camera views for a few days now, and all the other solutions require payment. Do you plan on making this open source? or is this more of a private project?

**Comment by Ezharjan** [comment]
I didn't encounter such a problem when I used it, I carefully checked your problem and guessed whether it was caused by the system environment. The vast majority of causes for error about 80004005 which is shown in `H264Encoder.log`  were about the system environment. Maybe you can check about it. _(The development environment I used is Windows 10, Unity 2018 4.16f1.)_

PS: Thanks. This is open source. The source code for H264Encoder.dll can be found in `Native~` folder and you can even redevelop it yourself. 
![图片](https://user-images.githubusercontent.com/60126466/111016421-e60a0600-83e8-11eb-8337-a820c4407d44.png)


_The audio part is left to be done._

**Comment by Ragingram2** [comment]
Ah I see, I believe we were using Unity 2020.2 Sadly we cant swap our environments, but thanks for the help. Again great project.
